resolving install status (#59)
* testing for outdated status during build

* removing reference to unused emotion library

* set push to master, run list commands before grep test

* first pass cleanup

* improve build test output

* improve build test output

* improve build test output

* improve build test output

* improve build test output

* improve build test output

* version bump

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,7 +2,7 @@ name: Build
 
 on:
   push:
-    branches: main
+    branches: master
   pull_request:
     branches: '*'
 
@@ -51,8 +51,14 @@ jobs:
         jlpm
         jlpm run eslint:check
         python -m pip install .
-
-        jupyter server extension list 2>&1 | grep -ie "jupyterlab_slurm.*OK"
-
-        jupyter labextension list 2>&1 | grep -ie "jupyterlab-slurm.*enabled"
+        RED=`tput -T xterm setaf 1`
+        GREEN=`tput -T xterm setaf 2`
+        SERVER_EXT=`jupyter serverextension list 2>&1`
+        LAB_EXT=`jupyter labextension list 2>&1`
+        echo -n "server extension install "
+        grep -e "jupyterlab_slurm.*OK" <<< $SERVER_EXT && echo "${GREEN}PASS" || echo "${RED}FAIL"
+        echo "$SERVER_EXT"
+        echo -n "lab extension install "
+        grep -e "jupyterlab-slurm.*enabled.*OK" <<< $LAB_EXT && echo "${GREEN}PASS" || echo "${RED}FAIL"
+        echo "$LAB_EXT"
         python -m jupyterlab.browser_check
