improve build test output

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -47,14 +47,13 @@ jobs:
     - name: Install dependencies
       run: python -m pip install -U jupyterlab~=3.0 jupyter_packaging~=0.7.9
     - name: Build the extension
+      env:
+        RED: `tput setaf 1`
+        GREEN: `tput setaf 2`
       run: |
         jlpm
         jlpm run eslint:check
         python -m pip install .
-
-        jupyter server extension list
-        jupyter server extension list 2>&1 | grep -ie "jupyterlab_slurm.*OK"
-
-        jupyter labextension list
-        jupyter labextension list 2>&1 | grep -ie "jupyterlab-slurm.*enabled.*OK"
+        jupyter server extension list 2>&1 | grep -ie "jupyterlab_slurm.*OK" && echo "${GREEN}PASS" || echo "${RED}FAIL"
+        jupyterlab-slurm % jupyter labextension list 2>&1 | grep -ie "jupyterlab-slurm.*enabled.*OK" && echo "${GREEN}PASS" || echo "${RED}FAIL"
         python -m jupyterlab.browser_check
